### ISSUE TITLE
Buddy-core doesn't allow renaming Plugin Handler

### ISSUE THREAD

**Issue by djklim87** [manticoresoftware/manticoresearch-buddy#273]

**Comment by djklim87** [comment]
```
WARNING: [BUDDY] invalid output, should be 'Buddy ver, started address:port', got 'Error while initialization: #0 /workdir/vendor/manticoresoftware/buddy-core/src/Plugin/Pluggable.php(351): Manticoresearch\Buddy\Core\Plugin\Pluggable->registerHooks()
#1 /workdir/src/Lib/QueryProcessor.php(125): Manticoresearch\Buddy\Core\Plugin\Pluggable->fetchCorePlugins()
#2 /workdir/src/main.php(29): Manticoresearch\Buddy\Base\Lib\QueryProcessor::init()
#3 {main}
```

Cause Handler name already hardcoded [here](https://github.com/manticoresoftware/buddy-core/blob/main/src/Plugin/Pluggable.php#L427)

**Comment by donhardman** [comment]
As discussed today, the place where we have hardcoded "Handler" is a "TODO" item that we should fix in the future. Due to an issue before, we implemented it in that way, but it's something to consider and fix later on.

We don't have this task as a blocker since there's no immediate need to change the name. We decided to postpone it because all plugins will be self-sufficient. Due to the modification and paradigm shift, we'll also fix this issue in the hooks system by moving things into plugins when the Modify Table is affected. The hook is used by sharding, but it also has a comment that it's a temporary solution until we figure out the right one.

The hooks were implemented solely for using the plugin system and are not yet finished, so it's a consideration for the future. For now, there's no reason to work on it since we probably won't need to use it again for future tasks.

As decided before, we will return to this task once we really need it. Additionally, as an idea, we will prepare the rules of the paradigm that we should follow while developing Buddy, which will help us avoid confusion in the future.
