### ISSUE TITLE
Please consider re-writing the buddy in a respectable programming language.. 

### ISSUE THREAD

**Issue by skyscooby** [manticoresoftware/manticoresearch-buddy#407]
### Proposal:

Go-lang, Rust, C#. Cripes dare I say Python?? Even Ruby would be better than PHP.. Why PHP... the only language with a configuration file.

It's almost 2025...  

### Checklist:

<sup>To be completed by the assignee. Check off tasks that have been completed or are not applicable.</sup>
<details>

- [ ] Implementation completed
- [ ] Tests developed
- [ ] Documentation updated
- [ ] Documentation reviewed
- [ ] Changelog updated
- [x] OpenAPI YAML updated and issue created to rebuild clients

</details>

**Comment by skyscooby** [comment]
Nevermind... :/

**Comment by sanikolaev** [comment]
> Why PHP

Our team chose this language mainly because we have the most experience with it after C++. Currently, we're experimenting with integrating Rust into our core C++ code, and so far, the results are promising. This won't replace Buddy for now but will serve a very specific purpose: enabling the core C++ code to access [https://github.com/huggingface/candle](https://github.com/huggingface/candle), which is written in Rust, with minimal resource and performance overhead. In the future, we might consider integrating more Rust-based components with C++. 

However, it's important to differentiate between use cases:
- Some tasks, like auto-sharding orchestration, don’t need high performance but involve complex logic. These are easier to implement and debug in high-level languages like PHP.
- On the other hand, tasks that require high performance need direct memory access from the C++ code to the library. In such cases, languages like PHP, Go, or Python are unsuitable. A low-level technology is essential for these scenarios.
